### ISSUE TITLE
bugs in demo_video/demo.py

### ISSUE THREAD

**Issue by zhangzscn** [SysCV/MaskFreeVIS#13]
python demo_video/demo.py --config-file=configs/youtubevis_2019/video_maskformer2_R50_bs16_8ep.yaml 
 --video-input=video_det.avi --output=out/ --confidence-threshold=0.5

[07/26 14:17:12 detectron2]: Arguments: Namespace(confidence_threshold=0.5, config_file='configs/youtubevis_2019/video_maskformer2_R50_bs16_8ep.yaml', input=None, opts=[], output='out/', save_frames=False, video_input='video_det.avi')
[07/26 14:17:13 d2.checkpoint.detection_checkpoint]: [DetectionCheckpointer] Loading from /mnt/data1/代码/深度学习/MaskFreeVIS/model_final_r50_0466.pth ...
[07/26 14:17:13 fvcore.common.checkpoint]: [Checkpointer] Loading from /mnt/data1/代码/深度学习/MaskFreeVIS/model_final_r50_0466.pth ...
Traceback (most recent call last):
  File "demo_video/demo.py", line 162, in <module>
    predictions, visualized_output = demo.run_on_video(vid_frames,args.confidence_threshold)
  File "/mnt/data1/代码/深度学习/MaskFreeVIS/demo_video/predictor.py", line 46, in run_on_video
    predictions = self.predictor(frames)
  File "/mnt/data1/代码/深度学习/MaskFreeVIS/demo_video/predictor.py", line 111, in __call__
    predictions = self.model([inputs])
  File "/home/zhangzs36/anaconda3/envs/maskfreevis/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/mnt/data1/代码/深度学习/MaskFreeVIS/demo_video/../mask2former_video/video_maskformer_model.py", line 291, in forward
    features = self.backbone(images.tensor)
  File "/home/zhangzs36/anaconda3/envs/maskfreevis/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/mnt/data1/代码/深度学习/detectron2/detectron2/modeling/backbone/resnet.py", line 445, in forward
    x = self.stem(x)
  File "/home/zhangzs36/anaconda3/envs/maskfreevis/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/mnt/data1/代码/深度学习/detectron2/detectron2/modeling/backbone/resnet.py", line 356, in forward
    x = self.conv1(x)
  File "/home/zhangzs36/anaconda3/envs/maskfreevis/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/mnt/data1/代码/深度学习/detectron2/detectron2/layers/wrappers.py", line 131, in forward
    x = self.norm(x)
  File "/home/zhangzs36/anaconda3/envs/maskfreevis/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/mnt/data1/代码/深度学习/detectron2/detectron2/layers/batch_norm.py", line 58, in forward
    return F.batch_norm(
  File "/home/zhangzs36/anaconda3/envs/maskfreevis/lib/python3.8/site-packages/torch/nn/functional.py", line 2281, in batch_norm
    return torch.batch_norm(
RuntimeError: cuDNN error: CUDNN_STATUS_NOT_SUPPORTED. This error may appear if you passed in a non-contiguous input.

Package                       Version            Editable project location
----------------------------- ------------------ -----------------------------
absl-py                       1.4.0
antlr4-python3-runtime        4.9.3
black                         23.7.0
cachetools                    5.3.1
certifi                       2023.7.22
charset-normalizer            3.2.0
click                         8.1.6
cloudpickle                   2.2.1
contourpy                     1.1.0
cycler                        0.11.0
Cython                        3.0.0
detectron2                    0.6                /mnt/data1/代码/深度学习/detectron2
filelock                      3.12.2
fonttools                     4.41.1
fsspec                        2023.6.0
fvcore                        0.1.5.post20221221
google-auth                   2.22.0
google-auth-oauthlib          1.0.0
grpcio                        1.56.2
h5py                          3.9.0
huggingface-hub               0.16.4
hydra-core                    1.3.2
idna                          3.4
imageio                       2.31.1
importlib-metadata            6.8.0
importlib-resources           6.0.0
iopath                        0.1.9
kiwisolver                    1.4.4
lazy_loader                   0.3
Markdown                      3.4.4
MarkupSafe                    2.1.3
matplotlib                    3.7.2
MultiScaleDeformableAttention 1.0
mypy-extensions               1.0.0
networkx                      3.1
numpy                         1.24.4
oauthlib                      3.2.2
omegaconf                     2.3.0
opencv-python                 4.8.0.74
packaging                     23.1
pathspec                      0.11.1
Pillow                        9.3.0
pip                           23.1.2
platformdirs                  3.9.1
portalocker                   2.7.0
protobuf                      4.23.4
pyasn1                        0.5.0
pyasn1-modules                0.3.0
pycocotools                   2.0.6
pyparsing                     3.0.9
python-dateutil               2.8.2
PyWavelets                    1.4.1
PyYAML                        6.0.1
requests                      2.31.0
requests-oauthlib             1.3.1
rsa                           4.9
safetensors                   0.3.1
scikit-image                  0.21.0
scipy                         1.10.1
setuptools                    67.8.0
shapely                       2.0.1
six                           1.16.0
submitit                      1.4.5
tabulate                      0.9.0
tensorboard                   2.13.0
tensorboard-data-server       0.7.1
termcolor                     2.3.0
tifffile                      2023.7.10
timm                          0.9.2
tomli                         2.0.1
torch                         1.9.0
torchvision                   0.10.0
tqdm                          4.65.0
typing_extensions             4.6.3
urllib3                       1.26.16
Werkzeug                      2.3.6
wheel                         0.38.4
yacs                          0.1.8
zipp                          3.16.2

**Comment by kiwi12777** [comment]
May I ask if you have resolved it? What method was used to solve it？
